name: Delete all the candidates
on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        run: |
          IP=$(curl --request POST --url 'https://reclutapp-backend.vercel.app/api/auth/login' --header "Content-Type: application/json" -d '{"email": "andres@gmail.com", "password": "1234"}')
      - name: Obtain the token
        run: |
          token=${IP:10:164}
      - name: Delete the candidates
        run: |
          curl --request POST --url 'https://reclutapp-backend.vercel.app/api/candidates/delete' --header "authorization: ${token}"
